apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "falcon-sensor-cleanup.fullname" . }}
  labels:
    app: "{{ include "falcon-sensor-cleanup.name" . }}"
    app.kubernetes.io/name: {{ include "falcon-sensor-cleanup.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: "kernel_sensor"
    crowdstrike.com/provider: crowdstrike
    helm.sh/chart: {{ include "falcon-sensor-cleanup.chart" . }}
    {{- if .Values.labels }}
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
  annotations:
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  {{- if .Values.annotations }}
    {{- range $key, $value := .Values.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "falcon-sensor-cleanup.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: "kernel_sensor"
      crowdstrike.com/provider: crowdstrike
  template:
    metadata:
      annotations:
        {{ .Values.podAnnotationKey }}: disabled
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      labels:
        app: "{{ include "falcon-sensor-cleanup.name" . }}"
        app.kubernetes.io/name: {{ include "falcon-sensor-cleanup.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/component: "kernel_sensor"
        crowdstrike.com/provider: crowdstrike
        helm.sh/chart: {{ include "falcon-sensor-cleanup.chart" . }}
        {{- if .Values.labels }}
        {{- range $key, $value := .Values.labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
        {{ include "falcon-sensor-cleanup.workloadCleanupAllowlistLabel" . }}
    spec:
    {{- if and (.Values.image.pullSecrets) (.Values.image.registryConfigJSON) }}
      {{- fail "image.pullSecrets and image.registryConfigJSON cannot be used together." }}
    {{- else }}
    {{- if or (.Values.image.pullSecrets) (.Values.image.registryConfigJSON) }}
      imagePullSecrets:
      {{- if .Values.image.pullSecrets }}
        - name: {{ .Values.image.pullSecrets }}
      {{- end }}
      {{- if .Values.image.registryConfigJSON }}
        - name: {{ include "falcon-sensor-cleanup.fullname" . }}-pull-secret-cleanup
      {{- end }}
    {{- end }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
      {{- with .Values.tolerations }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
    {{- end }}
      nodeSelector:
        kubernetes.io/os: linux
    {{- if .Values.nodeAffinity }}
      affinity:
        nodeAffinity:
        {{- with .Values.nodeAffinity }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
    {{- end }}
      initContainers:
      - name: cleanup-opt-crowdstrike
        image: "{{ include "falcon-sensor-cleanup.image" . }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        command:
          - /bin/bash
        args:
          - '-c'
          - >-
            echo "Running /opt/CrowdStrike/falcon-daemonset-init -u";
            /opt/CrowdStrike/falcon-daemonset-init -u
        {{- if or .Values.gke.autopilot .Values.resources }}
        resources:
          requests:
            cpu: 10m
            ephemeral-storage: 100Mi
            memory: 50Mi
          limits:
            cpu: 10m
            ephemeral-storage: 100Mi
            memory: 50Mi
        {{- end }}
        securityContext:
          runAsUser: 0
          privileged: true
          allowPrivilegeEscalation: true
        {{- if .Values.gke.autopilot }}
          readOnlyRootFilesystem: true
          capabilities:
            add:
              - SYS_ADMIN
              - SYS_PTRACE
              - SYS_CHROOT
              - DAC_READ_SEARCH
        {{- else }}
          readOnlyRootFilesystem: false
        {{- end }}
      containers:
      - name: cleanup-sleep
        image: "{{ include "falcon-sensor-cleanup.image" . }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        args:
        - -c
        - sleep infinity
        command:
        - /bin/bash
        {{- if or .Values.gke.autopilot .Values.resources }}
        resources:
          requests:
            cpu: 10m
            ephemeral-storage: 100Mi
            memory: 50Mi
          limits:
            cpu: 10m
            ephemeral-storage: 100Mi
            memory: 50Mi
        {{- end }}
        securityContext:
          privileged: false
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: true
      serviceAccountName: {{ .Values.serviceAccount.name }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriod }}
      hostPID: true
