{{- if or .Values.container.enabled .Values.node.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "falcon-sensor.fullname" . }}-access-binding
  labels:
    app: {{ include "falcon-sensor.name" . }}
    {{- include "falcon-sensor.labels" . | nindent 4 }}
    {{- if .Values.container.enabled }}
    app.kubernetes.io/component: "container_sensor"
    {{ else if .Values.node.enabled }}
    app.kubernetes.io/component: "kernel_sensor"
    {{ end -}}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "falcon-sensor.fullname" . }}-access-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
