{{- if or .Values.container.enabled .Values.node.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "falcon-sensor.fullname" . }}-access-role
  labels:
    app: {{ include "falcon-sensor.name" . }}
    {{- include "falcon-sensor.labels" . | nindent 4 }}
    {{- if .Values.container.enabled }}
    app.kubernetes.io/component: "container_sensor"
    {{ else if .Values.node.enabled }}
    app.kubernetes.io/component: "kernel_sensor"
    {{ end -}}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - secrets
  {{- if .Values.node.enabled }}
  - pods
  - services
  - nodes
  - daemonsets
  - replicasets
  - deployments
  - jobs
  - ingresses
  - cronjobs
  - persistentvolumes
  {{- end }}
  verbs:
  - get
  {{- if .Values.node.enabled }}
  - watch
  - list
  {{- end }}
{{- end }}
