{{- if .Values.container.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "falcon-sensor.name" . }}-injector
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "falcon-sensor.name" . }}
    {{- include "falcon-sensor.labels" . | nindent 4 }}
    app.kubernetes.io/component: "container_sensor"
spec:
  selector:
    app: {{ include "falcon-sensor.name" . }}-injector
    app.kubernetes.io/name: {{ include "falcon-sensor.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "container_sensor"
  ports:
    - name: https
      port: 443
      targetPort: https
{{- end }}
