{{- if .Values.node.enabled }}
{{- if or .Values.node.daemonset.priorityClassCreate .Values.node.gke.autopilot }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "falcon-sensor.priorityClassName" . }}
  labels:
    app: {{ include "falcon-sensor.name" . }}
    {{- include "falcon-sensor.labels" . | nindent 4 }}
    app.kubernetes.io/component: "kernel_sensor"
value: {{ .Values.node.daemonset.priorityClassValue }}
globalDefault: false
description: "This priority class would be used to deploy CrowdStrike node sensor for GKE Autopilot clusters."
{{- end }}
{{- end }}
